### ISSUE TITLE
BUG: No support for M1 / arm64

### ISSUE THREAD

**Issue by danorton** [johnhcc/homebrew-gs-x11#3]
The brew install command fails with an error about missing arm64 support:
````clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/gpcl6] Error 1
make: *** Waiting for unfinished jobs....
Undefined symbols for architecture arm64:
  "_png_init_filter_functions_neon", referenced from:
      _png_read_filter_row in pngrutil.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/gs] Error 1
Undefined symbols for architecture arm64:
  "_png_init_filter_functions_neon", referenced from:
      _png_read_filter_row in pngrutil.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/gxps] Error 1````

**Comment by johnhcc** [comment]
Thanks. If you make any headway on this or have ideas, let me know. I don't have immediate access to an M1 machine to debug this - but one thing I can try is to update the formula to mirror the CORE version, which presumably does work on ARM processors. I will try to get to that this weekend.

**Comment by johnhcc** [comment]
Did the error occur installing ghostscript-x11, or gv?

**Comment by johnhcc** [comment]
I've made some updates. Please try the install again using the following commands on your M1 and let me know what happens. The last step may take 10 minutes or more:

```
brew update
brew upgrade
brew uninstall --ignore-dependencies --force johnhcc/gs-x11/ghostscript-x11
brew install johnhcc/gs-x11/ghostscript-x11
```

**Comment by danorton** [comment]
It installs, but when I run gv, it reports "gv: Unable to open the display."
MacBook Air (M1, 2020)
gv 3.7.4

**Comment by johnhcc** [comment]
Do you have XQuartz installed (https://www.xquartz.org)?
- If "no", please download and install it, logout or reboot, then login again.  Then try opening gv.
- If "yes", please start it by going to Applications / Utilities / XQuartz.  Then click Applications in the menubar at the top of the screen, and select "xlogo".  Does it bring up a window showing a stylized "X" logo?

**Comment by johnhcc** [comment]
I'm going to close this issue. Feel free to reply, though, if the problem persists after considering the XQuartz instructions above.
